#ifndef AFUNCTIONLIBRARYSDK_C_MACROS_H
#define AFUNCTIONLIBRARYSDK_C_MACROS_H

#define AFUNCTIONLIBRARY_NAMESPACE
#define PRIVATE_AFUNCTIONLIBRARY_OPEN_NAMESPACE
#define PRIVATE_AFUNCTIONLIBRARY_CLOSE_NAMESPACE

#endif /* AFUNCTIONLIBRARYSDK_C_MACROS_H */
