#ifndef AFUNCTIONLIBRARYSDK_CPP_MACROS_H
#define AFUNCTIONLIBRARYSDK_CPP_MACROS_H

#define AFUNCTIONLIBRARY_NAMESPACE afl::
#define PRIVATE_AFUNCTIONLIBRARY_OPEN_NAMESPACE namespace afl {
#define PRIVATE_AFUNCTIONLIBRARY_CLOSE_NAMESPACE }

#endif /* AFUNCTIONLIBRARYSDK_CPP_MACROS_H */
