#ifndef AFUNCTIONLIBRARYSDK_OPTIMIZEFUNCTIONAPI_DEFINITIONS_HPP
#define AFUNCTIONLIBRARYSDK_OPTIMIZEFUNCTIONAPI_DEFINITIONS_HPP

namespace afl
{
    constexpr const char* k_C_API_OptimizeFunctionStringFeatureGroupName = "__afl_c_api_optimize_function_string__";
#define __AFL_C_API_OPTIMIZE_FUNCTION_STRING_FEATURE_GROUP_NAME__ __afl_c_api_optimize_function_string__
    constexpr const char* k_C_API_OptimizeFunctionStringDefaultFeatureName = "__afl_c_api_optimize_function_string_default_feature__";
#define __AFL_C_API_OPTIMIZE_FUNCTION_STRING_DEFAULT_FEATURE_NAME__ __afl_c_api_optimize_function_string_default_feature__
    constexpr const char* k_CPP_API_OptimizeFunctionStringFeatureGroupName = "__afl_cpp_api_optimize_function_string__";
#define __AFL_CPP_API_OPTIMIZE_FUNCTION_STRING_FEATURE_GROUP_NAME__ __afl_cpp_api_optimize_function_string__
    constexpr const char* k_CPP_API_OptimizeFunctionStringDefaultFeatureName = "__afl_cpp_api_optimize_function_string_default_feature__";
#define __AFL_CPP_API_OPTIMIZE_FUNCTION_STRING_DEFAULT_FEATURE_NAME__ __afl_cpp_api_optimize_function_string_default_feature__

    constexpr const char* k_C_API_OptimizeFunctionSyntaxTreeFeatureGroupName = "__afl_c_api_optimize_function_syntax_tree__";
#define __AFL_C_API_OPTIMIZE_FUNCTION_SYNTAX_TREE_FEATURE_GROUP_NAME__ __afl_c_api_optimize_function_syntax_tree__
    constexpr const char* k_C_API_OptimizeFunctionSyntaxTreeDefaultFeatureName = "__afl_c_api_optimize_function_syntax_tree_default_feature__";
#define __AFL_C_API_OPTIMIZE_FUNCTION_SYNTAX_TREE_DEFAULT_FEATURE_NAME__ __afl_c_api_optimize_function_syntax_tree_default_feature__
    constexpr const char* k_CPP_API_OptimizeFunctionSyntaxTreeFeatureGroupName = "__afl_cpp_api_optimize_function_syntax_tree__";
#define __AFL_CPP_API_OPTIMIZE_FUNCTION_SYNTAX_TREE_FEATURE_GROUP_NAME__ __afl_cpp_api_optimize_function_syntax_tree__
    constexpr const char* k_CPP_API_OptimizeFunctionSyntaxTreeDefaultFeatureName = "__afl_cpp_api_optimize_function_syntax_tree_default_feature__";
#define __AFL_CPP_API_OPTIMIZE_FUNCTION_SYNTAX_TREE_DEFAULT_FEATURE_NAME__ __afl_cpp_api_optimize_function_syntax_tree_default_feature__
}

#endif //AFUNCTIONLIBRARYSDK_OPTIMIZEFUNCTIONAPI_DEFINITIONS_HPP
